version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE}
      INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
      INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping", "--host", "http://localhost:8086"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kodam-influx-api
    env_file:
      - .env
    environment:
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
    ports:
      - "3000:3000"
    depends_on:
      influxdb:
        condition: service_healthy
    restart: always
    networks:
      - backend

volumes:
  influxdb-data:
  influxdb-config:

networks:
  backend:
    driver: bridge